"""V1 explainable GPIC caption-to-concept baseline."""

from gpic_concepts_v1.schema import (
    PIPELINE_VERSION,
    CanonicalEdge,
    CanonicalMention,
    CaptionRecord,
    CountRow,
    FactRow,
    RawEdge,
    RawMention,
    make_global_id,
    make_local_id,
)
from gpic_concepts_v1.stage1_loader import (
    build_stage1_summary,
    iter_stage1_records,
    run_stage1_records,
)
from gpic_concepts_v1.stage1 import (
    GPIC_SENTENCE_CAPTION_TYPES,
    GPIC_TAG_LIST_CAPTION_TYPES,
    TAG_LIST_SKIP_REASON,
    CaptionShapeError,
    caption_shape_from_gpic_caption_type,
    caption_shape_from_gpic_row,
    determine_caption_shape,
    make_caption_record_from_gpic_row,
    make_caption_record,
    normalize_caption_shape,
)
from gpic_concepts_v1.stage2_preprocess import (
    ObjectMweEntry,
    ProtectedSpanRecord,
    Stage2DependencyError,
    Stage2InputError,
    Stage2Record,
    load_object_mwes,
    make_stage2_nlp,
    preprocess_gpic_sentence_row,
    preprocess_text,
    run_stage2_preprocess,
)
from gpic_concepts_v1.stage3_annotate import (
    DEFAULT_STAGE3_MODEL,
    Stage3DependencyError,
    Stage3Record,
    annotate_gpic_sentence_row,
    annotate_text,
    make_stage3_nlp,
    run_stage3_annotate,
)
from gpic_concepts_v1.stage4_extract_raw import (
    RawExtractionResult,
    extract_raw_concepts_from_stage3_record,
    run_stage4_extract_raw,
)
from gpic_concepts_v1.stage5_canonicalize import (
    CanonicalizationResult,
    LexiconValue,
    Stage5Lexicons,
    canonicalize_raw_graph,
    load_stage5_lexicons,
    run_stage5_canonicalize,
)

__all__ = [
    "PIPELINE_VERSION",
    "CanonicalEdge",
    "CanonicalMention",
    "CaptionRecord",
    "CountRow",
    "FactRow",
    "RawEdge",
    "RawMention",
    "GPIC_SENTENCE_CAPTION_TYPES",
    "GPIC_TAG_LIST_CAPTION_TYPES",
    "TAG_LIST_SKIP_REASON",
    "CaptionShapeError",
    "caption_shape_from_gpic_caption_type",
    "caption_shape_from_gpic_row",
    "determine_caption_shape",
    "make_caption_record_from_gpic_row",
    "make_caption_record",
    "normalize_caption_shape",
    "make_global_id",
    "make_local_id",
    "build_stage1_summary",
    "iter_stage1_records",
    "run_stage1_records",
    "ObjectMweEntry",
    "ProtectedSpanRecord",
    "Stage2DependencyError",
    "Stage2InputError",
    "Stage2Record",
    "load_object_mwes",
    "make_stage2_nlp",
    "preprocess_gpic_sentence_row",
    "preprocess_text",
    "run_stage2_preprocess",
    "DEFAULT_STAGE3_MODEL",
    "Stage3DependencyError",
    "Stage3Record",
    "annotate_gpic_sentence_row",
    "annotate_text",
    "make_stage3_nlp",
    "run_stage3_annotate",
    "RawExtractionResult",
    "extract_raw_concepts_from_stage3_record",
    "run_stage4_extract_raw",
    "CanonicalizationResult",
    "LexiconValue",
    "Stage5Lexicons",
    "canonicalize_raw_graph",
    "load_stage5_lexicons",
    "run_stage5_canonicalize",
]
